# Generated by Django 5.2.11 on 2026-02-25 18:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cinemas', '0001_initial'),
        ('screenings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_code', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Код бронирования')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Цена')),
                ('status', models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('confirmed', 'Подтверждено'), ('cancelled', 'Отменено'), ('used', 'Использовано')], default='confirmed', max_length=20, verbose_name='Статус')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qrcodes/', verbose_name='QR-код')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('screening', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='screenings.screening', verbose_name='Сеанс')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='cinemas.seat', verbose_name='Место')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='booking_user_status_idx'), models.Index(fields=['screening'], name='booking_screening_idx'), models.Index(fields=['created_at'], name='booking_created_idx'), models.Index(fields=['screening', 'seat', 'status'], name='booking_availability_idx'), models.Index(fields=['status'], name='booking_status_idx')],
                'unique_together': {('screening', 'seat')},
            },
        ),
    ]
