# Generated by Django 5.2.11 on 2026-02-25 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('duration', models.PositiveIntegerField(default=120, verbose_name='Длительность (минут)')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='posters/', verbose_name='Постер')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='Дата выхода')),
                ('director', models.CharField(blank=True, max_length=100, verbose_name='Режиссер')),
                ('cast', models.TextField(blank=True, verbose_name='В ролях')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Фильм',
                'verbose_name_plural': 'Фильмы',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['title'], name='movie_title_idx'), models.Index(fields=['release_date'], name='movie_release_date_idx'), models.Index(fields=['is_active'], name='movie_active_idx'), models.Index(fields=['release_date', 'is_active'], name='movie_release_active_idx'), models.Index(fields=['director'], name='movie_director_idx')],
            },
        ),
    ]
