# Generated by Django 5.2.11 on 2026-02-25 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CinemaHall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название зала')),
                ('rows', models.PositiveIntegerField(verbose_name='Количество рядов')),
                ('seats_per_row', models.PositiveIntegerField(verbose_name='Мест в ряду')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Кинозал',
                'verbose_name_plural': 'Кинозалы',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='hall_name_idx'), models.Index(fields=['is_active'], name='hall_active_idx')],
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.PositiveIntegerField(verbose_name='Ряд')),
                ('number', models.PositiveIntegerField(verbose_name='Место')),
                ('seat_type', models.CharField(choices=[('standard', 'Обычное'), ('vip', 'VIP')], default='standard', max_length=10, verbose_name='Тип места')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='cinemas.cinemahall', verbose_name='Зал')),
            ],
            options={
                'verbose_name': 'Место',
                'verbose_name_plural': 'Места',
                'ordering': ['row', 'number'],
                'indexes': [models.Index(fields=['hall'], name='seat_hall_idx'), models.Index(fields=['seat_type'], name='seat_type_idx'), models.Index(fields=['row', 'number'], name='seat_row_number_idx')],
                'unique_together': {('hall', 'row', 'number')},
            },
        ),
    ]
